baseURL = "https://yhrgintoki.github.io/"
languageCode = "en-us"
title = "Robot Assisted Feeding"
theme = "hugo-serif-theme"

# Highlighting config (Pygments)
# It is (currently) not in use, but you can do ```go in a content file if you want to.
pygmentsCodeFences = true

pygmentsOptions = ""
# Use the Chroma stylesheet
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = false

[params]
  google_analytics_id="UA-146151202-1"

  [params.homepage_meta_tags]
    meta_description = "The Multi-agent System for non-Holonomic Racing (MuSHR) is an open-source robotic hardware and software platform for learning and researching AI in a the setting of autonomous vehicles and mobile robotics."
    meta_og_title = "MuSHR: The UW Open Racecar Project"
    meta_og_type = "website"
    meta_og_url = "https://prl-mushr.github.io"
    meta_og_image = "https://prl-mushr.github.io/imgs/single-car.jpg"
    meta_og_description = "The Multi-agent System for non-Holonomic Racing (MuSHR) is an open-source robotic hardware and software platform for learning and researching AI in a the setting of autonomous vehicles and mobile robotics."
    meta_twitter_card = "summary"
    meta_twitter_site = "@MichaloveJohan"
    meta_twitter_creator = "@MichaloveJohan"

# Main Menu

[[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 2

[[menu.main]]
    identifier = "demos"
    name = "Demos and Outreach"
    url = "/demos/"
    weight = 3

[[menu.main]]
    identifier = "datasets"
    name = "Open Datasets"
    url = "/datasets/"
    weight = 4

[[menu.main]]
    identifier = "hardware"
    name = "Open Hardware"
    url = "/hardware/"
    weight = 5

[[menu.main]]
    parent = "hardware"
    name = "Tactile Sensor"
    url = "/hardware/Gelsight-Mini Tactile Sensor/"
    weight = 5

[[menu.main]]
    parent = "hardware"
    name = "Wireless Perception Module"
    url = "/hardware/Wireless Perception Module/"
    weight = 5
[[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "/videos/"
    weight = 6

[[menu.main]]
    name = "People"
    url = "https://personalrobotics.cs.washington.edu/people/"
    weight = 7

[[menu.main]]
    identifier = "press"
    name = "Press"
    url = "/press/"
    weight = 8

# Footer Menu
[[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
